### ISSUE TITLE
image projection views are not correctly oriented to raw axis arrays

### ISSUE THREAD

**Issue by mlp6** [KitwareMedical/SlicerITKUltrasound#57]
Right now, the example data loads in 3 axis arrays:

1. `axial`
2. `lat`
3. `eleAngle`

The currently rendered frames then do not correspond to the anatomically-correct views.  The following labeling of the subpanels--from an anatomic perspective, for the given input arrays--should be:

1. `Coronal -> Axial`
2. `Sagital -> Coronal`
3. `Axial -> Sagital`

I will fork this repo to submit a PR to request this change be made.

**Comment by mlp6** [comment]
It would also help to rotate the `Axial` and `Coronal` planes to match clinically-standard views.

**Comment by thewtex** [comment]
@mlp6 :+1: sounds good. Changing the direction can be achieve by setting the `Direction` here:

  https://github.com/KitwareMedical/ITKUltrasound/blob/ec34fd1d22aef70b28c34605638b0df95ea8e03c/src/itkHDF5UltrasoundImageIO.cxx#L361-L446

see, e.g.

https://github.com/InsightSoftwareConsortium/ITK/blob/5c69d81e3001210f84729cc69fecad87d16ff25b/Modules/IO/NIFTI/src/itkNiftiImageIO.cxx#L1785-L1826

**Comment by mlp6** [comment]
Thanks @thewtex .  Since our input axis vector names are ambiguous w/r to absolute anatomic orientation, we might expose transposing view as a button to toggle instead of hard-coding an assumed view.

**Comment by thewtex** [comment]
:ok:
