### ISSUE TITLE
BUG: module not available to install via Extension Manager in recent versions of Slicer

### ISSUE THREAD

**Issue by mlp6** [KitwareMedical/SlicerITKUltrasound#72]
It looks like there might be a build problem with this extension, and it is no longer available to install in 3D Slicer via the Extension Manager (tested with `4.13.0-2022-01-21` (Windows nightly).

@thewtex this might need to be on your radar

**Comment by thewtex** [comment]
@mlp6 thanks for the note!

@jcfr took a quick look, it seems to be a CMake/ Python version issue.

**Comment by mlp6** [comment]
@thewtex @jcfr thanks!  It looked like it was still using Python 2.7, so I thought that may be an issue.  I'm going to use this module as the "base" for our other features, so getting this to compile and load up nicely will help a lot.  Thx!

**Comment by mlp6** [comment]
@thewtex @jcfr any updates in fixing this?  I'm happy to submit a PR if that would help, but I think that your more direct low-level knowledge of the CMake/Python2.7 -> 3 transition / implications might be valuable here.
